### ISSUE TITLE
add topic tags in About section

### ISSUE THREAD

**Issue by Beliavsky** [ralna/MJDP_software#3]
I suggest adding topics such as `numerical-optimization`, `constrained-optimization`, `cobyla` in the About section at https://github.com/ralna/MJDP_software

**Comment by nimgould** [comment]
Good idea. I have added suitable topics

**Comment by Beliavsky** [comment]
I suggest changing `derivate-free-optimization` to `derivative-free-optimization`, since no other project uses the former, and 41 use the latter.

**Comment by nimgould** [comment]
Ooops, my mistake. Fixed. Thank you
